In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import sympy as sp

In [6]:
0 + 0.5 * np.random.randn(10)

array([-0.34361817, -0.14055448, -0.09029247, -1.12324563, -0.18137664,
        0.35914834,  0.41147848, -0.32713519,  0.44001578, -0.20058703])

In [271]:
class LogisticRegression:
    
    def __init__(self, eta=0.1, n_iters=10):
        self.eta = eta
        self.n_iters = n_iters

    def z(self, X):
        return np.dot(X, self.weight_) + self.bias_
    
    def sigmoid(self, X):
        self.probabilities = 1 / (1 + np.exp(-self.z(X)))
        return self.probabilities
    
    def dL_w(self, X_train, y_pred, y_train):
        return 1/len(y_pred) * np.dot(X_train.T, y_pred - y_train)
    
    def dL_b(self, y_pred, y_train):
        return 1/len(y_pred) * np.sum(y_pred - y_train)


    def fit(self, X_train, y_train):
        self.weight_ = (0 + 0.5 * np.random.randn(X_train.shape[1])).T
        self.bias_ = 1

        for _ in range(0, self.n_iters):
            
            y_pred = self.sigmoid(X_train)
            
            self.weight_ = self.weight_ - self.eta * self.dL_w(X_train, y_pred, y_train)
            self.bias_ = self.bias_ - self.eta * self.dL_b(y_pred, y_train)

    
    def predict(self, X_test):

        #return self.sigmoid(X_test)
        return (self.sigmoid(X_test) > 0.5).astype(int)
        


In [67]:
from sklearn.datasets import load_iris

In [225]:
X = load_iris().data[:100]
y = load_iris().target[:100]

In [226]:
from sklearn.model_selection import train_test_split

In [227]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [267]:
model = LogisticRegression()
model.fit(X_train, y_train)

In [263]:
model.probabilities

array([0.40784202, 0.64773083, 0.71960805, 0.44199364, 0.73132178,
       0.46814366, 0.42922224, 0.69708166, 0.47642641, 0.41080057,
       0.68798869, 0.46289445, 0.4505656 , 0.39056305, 0.44215535,
       0.43956429, 0.6810982 , 0.69874806, 0.66765168, 0.73664284,
       0.67207503, 0.64155911, 0.71522997, 0.38645141, 0.44972998,
       0.68942141, 0.44564065, 0.70545905, 0.39814975, 0.42224261])

In [254]:
y_test

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0])

In [268]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1])

In [276]:
from sklearn.metrics import confusion_matrix, recall_score, precision_score

In [275]:
confusion_matrix(y_test, y_pred)

array([[ 5, 11],
       [ 0, 14]])

In [ ]:
recall_score(y_test, y_pred)
#TP / (TP + FN) or 1st column
#sensitivity

#how many positive cases we correctly predicted out of all positive cases

1.0

In [277]:
precision_score(y_test, y_pred)

0.56